-- 코드 초기값. 출처: vacation-support-admin-asis/admin/06-DOMAIN-CODES.md (AS-IS 화면 DOM 실측 value)
-- 라벨은 정본(06 문서 1절)으로 통일했다. AS-IS 에 코드가 없던 그룹(USE_STOP_RSN 등)은 이번에 새로 매긴 값이다 — 설계서 '확인 필요' 참고.
insert into vs_cd_c (cd_grp, cd, cd_nm, sort_ordg, up_cd, frst_reg_usr_id, frst_reg_pgm_id, last_mod_usr_id, last_mod_pgm_id)
select g, c, n, s, u, 'SYSTEM', 'INIT_SEED', 'SYSTEM', 'INIT_SEED'
from (values
-- 기업 참여 상태 (AS-IS prcsSts, 27종). up_cd = 단계
('JOIN_ST','00','심사중',1,'JDG'),
('JOIN_ST','20','정상접수',2,'JDG'),
('JOIN_ST','30','보완필요',3,'JDG'),
('JOIN_ST','32','심사미대상',4,'JDG'),
('JOIN_ST','34','참여취소(심사미대상)',5,'OUT'),
('JOIN_ST','40','선정대기',6,'SLCT'),
('JOIN_ST','50','선정완료',7,'SLCT'),
('JOIN_ST','60','계약완료',8,'CTRT'),
('JOIN_ST','62','미체결',9,'CTRT'),
('JOIN_ST','64','대기(후순위)',10,'CTRT'),
('JOIN_ST','66','계약파기(반려)',11,'OUT'),
('JOIN_ST','70','최종제출(등록완료)',12,'REG'),
('JOIN_ST','72','등록승인(입금중)',13,'DPST'),
('JOIN_ST','74','입금완료',14,'DPST'),
('JOIN_ST','75','참여취소(미입금)',15,'OUT'),
('JOIN_ST','76','참여개시',16,'OPR'),
('JOIN_ST','7600','참여개시(등록완료)',17,'OPR'),
('JOIN_ST','7609','참여개시(보완필요)',18,'OPR'),
('JOIN_ST','7610','참여개시(입금중)',19,'OPR'),
('JOIN_ST','7620','참여개시(입금완료)',20,'OPR'),
('JOIN_ST','7630','참여개시(추가취소)',21,'OPR'),
('JOIN_ST','7640','참여개시(추가완료)',22,'OPR'),
('JOIN_ST','80','이용정지',23,'END'),
('JOIN_ST','90','환불요청',24,'RFND'),
('JOIN_ST','92','환불대상',25,'RFND'),
('JOIN_ST','94','환불완료',26,'RFND'),
('JOIN_ST','96','환불실패',27,'RFND'),
-- 회원 상태
('MBR_ST','L','미가입',1,null),
('MBR_ST','N','이용중',2,null),
('MBR_ST','S','이용정지',3,null),
('MBR_ST','R','환불요청',4,null),
('MBR_ST','T','환불대상',5,null),
('MBR_ST','D','환불완료',6,null),
('MBR_ST','F','환불실패',7,null),
-- 근로자 심사 (신규)
('WRKR_JDG','WAIT','심사대기',1,null),
('WRKR_JDG','APV','승인',2,null),
('WRKR_JDG','SPLM','보완필요',3,null),
('WRKR_JDG','RJCT','반려',4,null),
-- 환불수단
('RFND_MTHD','A','기업(33%)+개인(67%)',1,null),
('RFND_MTHD','C','기업',2,null),
('RFND_MTHD','P','개인',3,null),
-- 기업구분
('CO_FG','1','소상공인',1,null),
('CO_FG','2','소기업',2,null),
('CO_FG','3','중기업',3,null),
('CO_FG','4','중견기업',4,null),
('CO_FG','5','비영리민간단체',5,null),
('CO_FG','6','사회복지법인·시설',6,null),
('CO_FG','7','의료법인',7,null),
-- 지원구분 · 사업 진행상태 (신규)
('SPRT_DIV','GNRL','일반',1,null),
('SPRT_DIV','DVLP','발전',2,null),
('SPRT_DIV','PRTN','동반성장',3,null),
('BIZ_PRGS_ST','RDY','준비',1,null),
('BIZ_PRGS_ST','RCRT','모집중',2,null),
('BIZ_PRGS_ST','JDG','심사중',3,null),
('BIZ_PRGS_ST','OPR','운영중',4,null),
('BIZ_PRGS_ST','END','종료',5,null),
-- 참여경로 (AS-IS joinChannel)
('JOIN_CHNL','1000001222','KCP 매스 마케팅',1,null),
('JOIN_CHNL','1000001182','사업 광고',2,null),
('JOIN_CHNL','1000001183','동반성장제도(타 기관을 통한 휴가비 추가 지원)',3,null),
('JOIN_CHNL','1000001184','재 참여기업',4,null),
('JOIN_CHNL','1000000719','언론 보도자료',5,null),
('JOIN_CHNL','1000000721','노동자 휴가지원사업 카카오톡 채널',6,null),
('JOIN_CHNL','1000000724','지인 추천',7,null),
('JOIN_CHNL','1000000726','타기관 홈페이지',8,null),
('JOIN_CHNL','1000000727','기타',9,null),
-- 이용정지 사유 (AS-IS 는 라벨만 확인 — 코드는 신규)
('USE_STOP_RSN','01','퇴사(이직)',1,null),
('USE_STOP_RSN','02','개인사유(근로자 자유의지)',2,null),
('USE_STOP_RSN','03','신분변경(대상 → 비대상)',3,null),
('USE_STOP_RSN','04','기업경영악화(인수/합병 등)',4,null),
('USE_STOP_RSN','05','복지제도 변경',5,null),
('USE_STOP_RSN','06','동반성장모델 지원 기한 종료',6,null),
('USE_STOP_RSN','99','기타',7,null),
-- 계정
('MNGR_DIV','KTO','한국관광공사',1,null),
('MNGR_DIV','EZW','현대이지웰',2,null),
('MNGR_DIV','COMP','참여기업',3,null),
-- 역할 (SB docs/permissions.md §2). up_cd = 소속 계정구분
('AUTH','AM','지원기관 마스터',1,'KTO'),
('AUTH','AL','지원기관 총괄',2,'KTO'),
('AUTH','AS','지원기관 담당자',3,'KTO'),
('AUTH','AV','지원기관 조회전용',4,'KTO'),
('AUTH','OM','운영사 마스터',5,'EZW'),
('AUTH','OO','운영사 운영자',6,'EZW'),
('AUTH','CM','기업 담당자',7,'COMP'),
('ACNT_ST','UNRG','미가입(담당자 등록만 됨)',1,null),
('ACNT_ST','USE','사용',2,null),
('ACNT_ST','DRMT','휴면',3,null),
('ACNT_ST','LOCK','잠금',4,null),
('ACNT_ST','STOP','사용중지',5,null),
('ACNT_APV','0','승인대기',1,null),
('ACNT_APV','3','승인',2,null),
('ACNT_APV','2','승인거부',3,null),
-- 이지웰 연동 상태
('LNK_ST','W','요청 대기',1,null),
('LNK_ST','C','완료',2,null),
('LNK_ST','F','실패(재시도)',3,null),
-- 이력 유형
('HIST_TYP','ST','상태변경',1,null),
('HIST_TYP','MEMO','관리자 메모',2,null),
('HIST_TYP','MOD','정보수정',3,null),
('HIST_TYP','SEND','알림발송',4,null),
('HIST_TYP','DPST','입금',5,null),
('HIST_TYP','LNK','이지웰 연동',6,null),
('HIST_TYP','DOWN','엑셀 다운로드',7,null),
('HIST_TYP','LGIN','접속',8,null),
('HIST_TYP','PRIV','개인정보 접근',9,null),
('HIST_TYP','CHK','다운로드 사유 확인',10,null),
-- 접속 결과 (vs_hist_h LGIN 의 aft_val)
('LGIN_RSLT','OK','로그인 성공',1,null),
('LGIN_RSLT','FAIL','로그인 실패',2,null),
('LGIN_RSLT','MFAF','2차 인증 실패',3,null),
('LGIN_RSLT','LOUT','로그아웃',4,null),
('LGIN_RSLT','AUTO','자동 로그아웃',5,null),
('LGIN_RSLT','DUP','중복 로그인 종료',6,null),
('LGIN_RSLT','LOCK','잠금 전환',7,null),
-- 게시물 구분 · 공지대상
('BBS_DIV','NOTI','공지사항',1,null),
('BBS_DIV','FAQ','자주 하는 질문',2,null),
('BBS_DIV','INQ','누리집 문의',3,null),
('BBS_DIV','RPT','부정행위 신고',4,null),
('BBS_DIV','REQ','기업 업무요청',5,null),
('BBS_DIV','DATA','자료실',6,null),
('BBS_DIV','MNUL','매뉴얼',7,null),
('BBS_DIV','POP','팝업',8,null),
('BBS_DIV','BNR','배너',9,null),
('NOTI_TGT','ALL','공통(누리집+기업)',1,null),
('NOTI_TGT','FO','누리집',2,null),
('NOTI_TGT','COMP','기업',3,null),
-- 참여불가
('BAN_DIV','COMP','참여불가 기업',1,null),
('BAN_DIV','MBR','참여불가 회원',2,null),
('DTCT_ROUT','S','스크래핑',1,null),
('DTCT_ROUT','R','신고',2,null),
('DTCT_ROUT','E','기타',3,null),
-- 부정행위 (vs_bbs_b RPT): 분류 · 처리상태(조치 4종, 신고·적발 공통) · 소명
('RPT_CTGR','WEB','누리집 신고',1,null),
('RPT_CTGR','MON','중고거래 모니터링 적발',2,null),
('RPT_ST','NEED','조치필요',1,null),
('RPT_ST','DONE','조치완료',2,null),
('RPT_ST','IMPS','조치불가',3,null),
('RPT_ST','PEND','미결',4,null),
('EXPL_ST','NSBM','소명서 미제출',1,null),
('EXPL_ST','SBMT','소명서 제출완료',2,null),
('EXPL_ST','RVKE','정지철회',3,null),
-- 발전모델 적용방식 · 등록구분 · 가상계좌 상태 · 서류 심사 (신규)
('DVLP_APLY_MTHD','COND','조건충족',1,null),
('DVLP_APLY_MTHD','DSGN','지정기업',2,null),
('REG_DIV','WEB','누리집 신청',1,null),
('REG_DIV','BULK','일괄등록',2,null),
('VACCT_ST','ISS','발급',1,null),
('VACCT_ST','EXP','만료',2,null),
('VACCT_ST','CLS','해지',3,null),
('FILE_JDG','OK','적합',1,null),
('FILE_JDG','HOLD','보완필요',2,null),
-- 첨부 구분
('FILE_DIV','EMPL','재직증빙서류',1,null),
('FILE_DIV','CORP','법인등기부등본',2,null),
('FILE_DIV','SMCO','중소기업확인서',3,null),
('FILE_DIV','MDCO','중견기업확인서',4,null),
('FILE_DIV','BZRG','사업자등록증·고유번호증',5,null),
('FILE_DIV','NPRF','비영리민간단체등록증',6,null),
('FILE_DIV','SWLF','사회복지법인설립허가증·시설신고증',7,null),
('FILE_DIV','BANK','통장사본',8,null),
('FILE_DIV','CNCL','취소공문',9,null),
('FILE_DIV','CNFM','참여확인서',10,null),
('FILE_DIV','DPST','입금확인증',11,null),
('FILE_DIV','CERT','참여증서',12,null),
('FILE_DIV','XLS','엑셀 일괄등록 원본',13,null),
('FILE_DIV','ATCH','게시물 첨부',14,null),
('FILE_DIV','PCIM','PC 이미지',15,null),
('FILE_DIV','MOIM','모바일 이미지',16,null),
('FILE_DIV','CAPT','적발 캡처',17,null),
('FILE_DIV','EXPL','소명서',18,null),
-- 은행 (금융결제원 표준, AS-IS selBankCd. 06 문서는 44종이라 적었지만 나열된 값은 43개)
('BANK','002','산업',1,null),('BANK','003','기업',2,null),('BANK','004','국민',3,null),('BANK','007','수협',4,null),
('BANK','011','농협',5,null),('BANK','012','지역농협/축협',6,null),('BANK','020','우리',7,null),('BANK','023','SC제일',8,null),
('BANK','027','한국씨티',9,null),('BANK','031','대구',10,null),('BANK','032','부산',11,null),('BANK','034','광주',12,null),
('BANK','035','제주',13,null),('BANK','037','전북',14,null),('BANK','039','경남',15,null),('BANK','045','새마을금고중앙회',16,null),
('BANK','048','신협',17,null),('BANK','050','상호저축',18,null),('BANK','054','HSBC',19,null),('BANK','060','BOA',20,null),
('BANK','064','산림조합중앙회',21,null),('BANK','071','우체국',22,null),('BANK','081','KEB하나',23,null),('BANK','088','신한',24,null),
('BANK','089','케이뱅크',25,null),('BANK','090','카카오뱅크',26,null),('BANK','218','KB증권',27,null),('BANK','238','미래에셋대우',28,null),
('BANK','240','삼성증권',29,null),('BANK','243','한국투자증권',30,null),('BANK','247','NH투자증권',31,null),('BANK','261','교보증권',32,null),
('BANK','262','하이투자증권',33,null),('BANK','263','현대차투자증권',34,null),('BANK','264','키움증권',35,null),('BANK','265','이베스트투자증권',36,null),
('BANK','266','SK증권',37,null),('BANK','267','대신증권',38,null),('BANK','269','한화투자증권',39,null),('BANK','278','신한금융투자',40,null),
('BANK','279','DB금융투자',41,null),('BANK','280','유진투자증권',42,null),('BANK','287','메리츠종합금융증권',43,null)
) as v(g, c, n, s, u);
